import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'react-tippy/dist/tippy.css'

import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import Experience from '../components/Experience'
import Featured from '../components/Featured'
import OtherProjects from '../components/OtherProjects'
import Contact from '../components/Contact'
import GetInTouch from '../components/GetInTouch'


export default function Home() {
  return (
    // <div className={styles.container}>
    <div className=''>
      <Head>
        <title>Jakob Potosme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async defer data-website-id="5d1e4d28-5d11-4f00-9f77-e30d81380182" src="https://umami-production-2ff2.up.railway.app/umami.js"></script>
        
      </Head>

      <Header />
      {/* <main className={styles.main}> */}
      <main className=" flex flex-col content-center  items-center  py-4">
      {/* <main className=' '> */}
        
        <Hero />
        <About />
        <Experience />
        <Featured />
        <GetInTouch />
        {/* <Contact /> */}
        {/* <OtherProjects /> */}
        
      </main>
      {/* <Footer /> */}
      <footer className={styles.footer}>
        <a
          
          target="_blank"
          rel="noopener noreferrer"
          className='mx-auto xs:pl-40'
        >
          © 2022 Potosme.
          
        </a>
        
      </footer>
    </div>
  )
}
