import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "react-tippy/dist/tippy.css";

import Header from "../components/Header";
import Hero from "../components/Hero";
import About from "../components/About";
import Experience from "../components/Experience";
import Featured from "../components/Featured";
import OtherProjects from "../components/OtherProjects";
import Contact from "../components/Contact";
import GetInTouch from "../components/GetInTouch";

export default function Home() {
  return (
    // <div className={styles.container}>
    <div className="mx-auto">
      <Head>
        <title>Jakob Potosme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          async
          defer
          data-website-id="ca0ef2a5-7ffc-4ead-89c7-64f04cb064ad"
          src="https://umami-production-e1da.up.railway.app/umami.js"
        ></script>
      </Head>

      <Header />
      {/* <main className={styles.main}> */}
      {/* <main className=" flex flex-col content-center  items-center  py-4"> */}
      {/* <main className=' '> */}

      <Hero />
      <About />
      <Experience />
      <Featured />
      <GetInTouch />
      {/* <Contact /> */}
      {/* <OtherProjects /> */}
      {/* </main> */}
      {/* <Footer /> */}
      <footer className="">
        <a
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center justify-center mx-auto border-t border-gray-500 py-2"
        >
          © 2022 Potosme.
        </a>
      </footer>
    </div>
  );
}
